version: '3'

services:
  v2ray:
    image: teddysun/xray:latest
    container_name: xray
    restart: always
    ports:
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./config:/etc/xray
      - ./logs:/var/log/xray
      - ./certs:/etc/ssl/xray
    environment:
      - TZ=Asia/Shanghai
    networks:
      - proxy-network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 86400 --cleanup
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge 